@extends('layouts.app')
@section('title', 'About')
@section('file', 'profile.txt')
@section('content')
<header class="page-heading"><p class="eyebrow">A LITTLE INTRODUCTION</p><h1>Behind the <em>pixels.</em></h1><p>Still learning, still making, still collecting interesting questions.</p></header>
<div class="page-content">
    <section class="profile-layout">
        <div class="window profile-id reveal"><div class="window-bar"><span>student-id.png</span><span aria-hidden="true">- □ ×</span></div><img src="{{ asset('images/profile/profile_photo.png') }}" alt="Angela Vania Sugiyono" width="467" height="545"><div class="id-details"><h2>{{ $profile['name'] }}</h2><p>{{ $profile['degree'] }} · ITS</p><span class="nrp">NRP {{ $profile['nrp'] }}</span></div></div>
        <div class="profile-story reveal"><p class="eyebrow">HI AGAIN, I’M ANGELA</p><h2>Curiosity is<br>my <em>starting point.</em></h2><p class="body-copy">{{ $profile['about'] }}</p><p class="body-copy muted">I care about work that is technically thoughtful and genuinely useful. This site is a scrapbook of the things I have learned, shipped, taught, and occasionally debugged at 2 a.m.</p><div class="button-row"><a class="button primary" href="{{ route('resume') }}">Open my résumé ↗</a><a class="text-link" href="{{ route('contact') }}">Let’s connect ↗</a></div></div>
    </section>
    <section class="academic-section"><div class="heading-row reveal"><div><p class="eyebrow">01 / WHAT I’M WORKING ON</p><h2>Learning out loud,<br><em>one lab at a time.</em></h2></div></div><div class="timeline experience-timeline">@foreach($profile['experience'] as $item)<article class="timeline-entry reveal"><div class="timeline-date">{{ $item['period'] }}</div><div><span class="eyebrow">{{ $item['organization'] }}</span><h3>{{ $item['role'] }}</h3><p>{{ $item['description'] }}</p></div></article>@endforeach</div></section>
    <section class="academic-section"><div class="heading-row reveal"><div><p class="eyebrow">02 / MY ACADEMIC JOURNEY</p><h2>A few chapters<br>of <em>learning.</em></h2></div><a class="text-link" href="{{ route('dashboard.index') }}">Academic dashboard ↗</a></div><div class="timeline">@foreach($profile['education'] as $education)<article class="timeline-entry reveal"><div class="timeline-date">{{ $education['period'] }}</div><div><h3>{{ $education['school'] }}</h3><p>{{ $education['degree'] }}</p><span class="score-label">{{ $loop->first ? 'Recorded GPA' : 'Recorded score' }}: {{ $education['score'] }}</span></div></article>@endforeach</div></section>
    <section class="academic-section"><div class="section-heading reveal"><p class="eyebrow">03 / MY LITTLE TOOLBOX</p><h2>Things I <em>work with.</em></h2></div><div class="content-grid toolbox"><article class="window reveal"><div class="window-bar"><span>technical-skills/</span><span aria-hidden="true">□</span></div><div class="toolbox-content"><p>Tools, languages & systems</p><div class="chip-list">@foreach($profile['skills'] as $skill)<span class="chip">{{ $skill }}</span>@endforeach</div></div></article><article class="window reveal"><div class="window-bar lavender-bar"><span>human-skills/</span><span aria-hidden="true">□</span></div><div class="toolbox-content"><p>The things that connect it all</p><div class="chip-list">@foreach($profile['soft_skills'] as $skill)<span class="chip lavender-chip">{{ $skill }}</span>@endforeach</div></div></article></div></section>
    <section class="academic-section"><div class="section-heading reveal"><p class="eyebrow">04 / COMMUNITY FILES</p><h2>Things are better<br><em>when built together.</em></h2></div><div class="community-grid">@foreach($profile['community'] as $item)<article class="panel reveal"><span class="file-corner" aria-hidden="true">TXT</span><p class="eyebrow">{{ $item['period'] }}</p><h3>{{ $item['role'] }}</h3><strong>{{ $item['organization'] }}</strong><p>{{ $item['description'] }}</p></article>@endforeach</div></section>
    <div class="bottom-note reveal"><span>Small steps deserve a little celebration.</span><a class="text-link" href="{{ route('collection') }}">Open achievements ↗</a></div>
</div>
@endsection
